name: Release ios prod

on:
  push:
    tags:        
      - v\d+\.\d+\.\d+
      - '!v*\.*\.*-rc'
      - '!v*\.*\.*-rc\.*'
      - '!v*\.*\.*-alpha'
      - '!v*\.*\.*-alpha\.*'

jobs:
  build:

    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode version
        run: sudo xcode-select -s '/Applications/Xcode_11.3.app/Contents/Developer'
      - name: Bundle install
        run: cd ./ios && bundle install
      - name: Setup flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "1.17.0"
          channel: "stable"
      - name: Install tools
        run: |
          flutter pub get
      - name: Deploy to Appstore
        run: |
          cd ./ios && bundle exec fastlane release
        env: 
          USERNAME: ${{secrets.USERNAME}}
          GITLAB_ACCESS_TOKEN: ${{secrets.GITLAB_ACCESS_TOKEN}}
          MATCH_PASSWORD: ${{secrets.MATCH_PASSWORD}}
          PRIVATE_GIT_URL: ${{secrets.PRIVATE_GIT_URL}}
          FASTLANE_PASSWORD: ${{secrets.FASTLANE_PASSWORD}}
          MATCH_KEYCHAIN_NAME: ${{ secrets.MATCH_KEYCHAIN_NAME }}
          MATCH_KEYCHAIN_PASSWORD: ${{ secrets.MATCH_KEYCHAIN_PASSWORD }}

          